env:
  global:
    - secure: l3GMV2MwgiA9aDUeYJdH7MN5Hzw3bssth5K1GiWQEfY2NN5JFf7QBwBEOA5LdpwC082wE0lNuWIvoH3G4U31aGW+nelhM9AVCRK+Sxii9HnHsi5MpkFY2IHtVxJfuEN7nboJB8W0XR7mFVthruz0V4pUSRup+tbEzg40ov8pM88S9LK1EGiK81w4oTxWdC8Usm7JmWU6LWANqZHgtGqMwgn9JBdDP836+1ctz1H58LYSUcPXntugUCmvv1+ZfM+qJxMJyC+oc/NhNTfTXIbLRfWYBcATm7nRqt8l0tvd08RRdXQT9GCiOtoIqHxsmuzPHyw7sS97AyF+5k1+SZ7VQrP4hzk4APOfxXqqlL9ezSV1ohXJh1RqyhS0O/I1aAm/YM9I4QmjKEOpyNp+EyoDz7chaDSpQHxUrZbOs3l7tZMd/Jw5PKRFdmEEJMYmgG8FO2lhBGHgEZ+Mmb+NUCpFCiIyzQ3Eli2AnXemNNrGxxz8LeA3Dt0fdic56hH6AThO9O7PWQDrxqvnFhnu01BFYmoUTuInp9ZXLCOA4gkTmDZdRBCqFqelEcRzP03s2r4SQAb/8psDqfv6+0TtPnRbAGPXcbzlpAZAWesst7a7oAZ7tZxyh2JWC9Otio/v121Ok1gQc5Y1+ycq6MhBMK+pRpKlugE/Jc6SYgWXFhRz1GA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Spam_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
