env:
  global:
    - secure: JqBgmAwia3Ks/S5JQ25RKjfyX2V36/u7qBdphW5oHklAO3NAboQGxr9xjpRmVBOf2JH/9YfFziZltu7SwQwzJRdNJLi4uBH+EC19VgauO1R5dauBG5k8BqWCpWkaDwSSVtXxQPirNUpXCP/xN4yEXXYBO7bjss96sBLzgPblNV8uoOk7/tlZBZnI9/GdHxkbX22YtbA+QYsPfUcmQABl5UYCwCq0kE7/n+ge0CFYGWZZct5lgZ81egWZYYw0nG2cxDwy6jpLTgG6ZAUHdB4AjdjTKYHCZ+gCypHXoqF8+KqrG0DNQep2nOEtQmlj788JMU2XSPokciFmlUgWFWzkcKLM4maDGM8OYGZzol7nUhs/QA0Hz7aOTqA4A99Yjte0+oE5jFcRjxkgq+SG1aXarqAB0oxfCrbmaz0sxVClSJ6szN7zk57btHiH+PB3eVuwKARwxXQ9o3InXoOi26/HIfB0STJajLpBlKFuYMtTM7OsOOUbuPgVn/YslRKO+DsQc9q2M1PkIKcQNtSbmsXa70p8bFung4h43ARwImmtG+KVac/vXmeRQYM+f7SZjhiyfUdy3kLuSDNvzHEc9LGJqej33eAmjO0X/SOnNkOhl3IgLMdPaaNAXT7A32HHQGuXSgoB1XhnUEF0Z1K4iAiNzdWN1Xo3XtMAEDldoTfKRvE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Spam_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
