env:
  global:
    - secure: bpKGtBvZ7wr691twwOC183FxSfYEtncgOKfo1gCGbTWtW8iE1dhGNZq7HMFdiaguUjYaGigSaTp2XqR0utsTybyJm6L7HGFL4XRp3VtPWI5OTZw5VGy/yCjLQk4sP/f7NaEJYDIYekgG/+53YmyortKLU4FIhsnchTPH4BxW42hpQJ3cW0o6ZRujGnx8+/hlqcIvjzCkz6rbFEszOXHSZJ9cOKJRo3uhIlYYdECV//4jGt2Q8o7/uw/RJ6jDnmiwKQzaXftDyaD/WK/+LMoLGiAadj8jQgvmO127tcaIwpaVHAVoLdyoZolqxoXZoPTPfvd+ErxVYzWAq6gmsxwU9hMxzsBE3HUwaFFlSqOB4uuI54rhV/AbCj1gQM6H7AoWPfTeQJgWmcpyB+Sj3gh3cqeB9HS4wgVPyoPRY3HxzFs2yIU7/2wMwLqhVNsVFcAsSQMDbxBmWqfrozPNEV4oA3Dm/6WJ1KLCFbJ/ynyfvbVvdRgarAajaxgR1GWc7+wBnxdGNTEAdu3Zf7AbkRwYBB7Tk7hbc/2nKPYzBep6nXMY+/nZS2+yL9pM8n1XT4ZYo9/zQ9fIOU3pk44mLkXpUWofsbvMZWWFX3I5sJlLf1c0zDEm0XWLDmee3Ugxu/HfjHbPTaKjVmSvPD0jZrZjgaaed2PUtCrLFCS5pn4j73I=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: funilrys@outlook.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Spam_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - sudo apt-get -y install python3-pip
  - sudo apt-get -y install dos2unix
  - pip3 install colorama

script:
  - export TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}
  - export GH_TOKEN=${GH_TOKEN}
  - export TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
  - export GIT_EMAIL=${GIT_EMAIL}
  - export GIT_NAME=${GIT_NAME}
  - python3 ./update_me.py

notifications:
  email: false
