env:
  global:
    - secure: jFMm8R4CKE2E2dwt8AiZT0RZCkn6schzHo5BKwuQTp99f7iCT8w0BmYK6AbgyxoKgNH1895BkKaFoV+t23ohIZMDrANGrIXZMnAdOoYcfJbqZ0ZuQl7u04N089gnSfv3ZjL2xaL8/dym5hziIYv2t1OJJHRGHIDp8+MaMR/E1hQrw3rr2wpH/9hgsonBsOQKThVAbjKtSJ9NAGQcfYJNev5dQ42mijEK9uwD3gwsnYnhE08rol/axECN3gFNwNSE3VuI94MddwwW/YfH9eW3GrSPiNXp6iw5Fl1WU2MkttTy/COA7RDIkknTPS9S5KisyrQuytb252/pucOqPuVBBBeKCWpGfDj/ema7zIhkSGTiQ9h3plDEju4MFwx0OtYEDxLKTtMExJVKLAiuKqBTtPrekdHkOnVdXDhszmv3uoUVrg0UgPkgCgInyJ0Xp3rrVb4ePCDuXCHvPiMmNrqWrr88qwH+n+K4zrRjJM7foimZown7zGskSmDJgI39uI/SsreF1nGlE78JMqS4z1g7WXcIMXpEMTpUeGHAWRPXulAzvap6u6QVsiwRRunm1ShKiNPoK9DEaF4B/1jfuBurZfUzv7Smm8MF6lQUjru4UIxldw4FD+FiHghu+DYVYjvteQcDMnRuf/9y0/rCvfftVqOXMb12UdyetLfB1cSrdRY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Spam_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
