env:
  global:
    - secure: qMsFvJYAhX1oSUDxCzyO372JDohgjszon3jXX2KTlzYhNuN5T8kiun7USJQbp5kr1/6xTCGjl/tJWWMcPBhasjUjdLh9PklhjA0ZHQ6LDWigJceKa+5PuKyZNlCxtHjzc+PfrnZEFeubKoGeOYje2RXPEG2UPzIcCjq+zsf3deR3hYUV9pKAq/XeH6JRmAMuDLzHM+9iUqHzBfLMB9g/sPsuL+931i9t62gVscLxrBfak5tXWFemjiWcn9fa6WC8EBxaVy1rKfs5634dSh3PErKSbO07/BPvBzvjee8E+GXk+eYjsksZeRmcFw9CGyp/+4OkS1Yje5Wd72B1n8ewKxJ2XjciYyeUsqsPUq/zbyDRAZemYx3clTtjSu7h/nfNcw1vDvRclCFXILHNuH+AfnYYqxgbLnWufO6tGkZ7gRaS1KnCy3S2BPb1lOHHbFl98iUWwDCj1wcXKwcIK65HDpMq4opHbysiW6bV6p+3igurkwqg0DfzHpDnEQea0smuC2zb8JwMlkdccsWUl9V9lvg+K79E3LmtcsuiDYILD0FLJDeJNYjpAfmJK7mkm3rSEWsOKeJFgKcXA527vhRIRBUIoZg1AOebQiuGCx8EUgqvRP32EKKccmz23AKaBIVIdRmByCqkjHf6O2vv3L/7EDDnTiFXsccgdMxdcccSkVs=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Spam_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
