env:
  global:
    - secure: HS6NAnz0PcnOOZvq8tDpKsYwRAQEbubYW2OnXkapNK7JAqKM9kCpygFVXG3ivBXrHIUP0mysWjia/4cxta5B+HXXkoNtTPdJiNtNJYYWPIPFS+hGB0vWJdeODzCvDtGtpGJPhHrCe6BjhJkkP1lTaJJTmwX+LlCgZFUPu69rCCf51qFrJEPFNdXDNQO0PP7yCSKXL5fv540CCEDNN8oW12kJtTCLErHcJHg+8X3mM8jR+zHDryLU1H/Yk7uNJtmSSMvV74bsAFsRoQ6HsfE0nUEY8JeJN0MLF8Tpo1bzaoqzWPLPlkXza5KK+YLuWXliayOt8wrYBy9zeP+drFiBl1zqia0XXwwdAdaaW/lG3VgxI1+NkMVYA9DLUoWKsIQYB4g6OB5IBWDY2TcYz21E2QPZOSgiG/RxkcttfqUsnbe3KCutiO95Riy9TftcLvSj1yp1+Ook9fl3hvpxpYfjrB88XzOTQYc8y3PJk4ct8SWacI7loqsaneBNWrs4gt9TyJq2P1nhEvmGu8k7P7WUutdMUEqhINGwa6rot41hpC2+VK+hj4x0HxtObHnYIS7hAduGKwQK8EYooZUNTiUtPLMNgfsVDiyiyy9A7WXnaFv/ZeUX1a6MZBuJgUnuFUbHgpxukqga56giWq3fb9qm023mkoXblFEB66kZjfXdLD4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Spam_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
