env:
  global:
    - secure: RdkV8HSqIF4lvUIziYW1Em9r2p18SroR+jWDOJe5iL/gS1alRJjmgNkPtXKAoXgwGNtKtEAQHufQ9bmO74PR0w+W3PrBTcLnRJwfPavXTQflZYkgDVJRhmKr9WZyAdEwSbL1WaWuFWXDtpf5GBFeWoaMIFd1DUUzPHEFblodqTIQ38tMd3CzGRNbJQIrIuh4COjKIIrG10vPnvVT9jrLqkgx2LyVmQDQrCCXTEKRQ6VhommN8bBldi9XR7Q2+PbwM4yPijT0I4KZeq6OBrdmHaL56t9WrYOMjolrvP9N0C9TMkGEvBm5ZGXumiLZtls6AzW85iBTZLws6x6oGA8dtrZ1qlUvX5/mb3wTP95+Iiwkn59Fx1zAyB5ecnwaAnkjmiYdF5cq9LH4wYVD1S+vZepkWNMqKjUs2LfrDMkmAq1DcsvoUXF6wBT9kAEVnaAp7lDxLY7JYH9NdQByVfzDriKk9/sLiF4mnvvH0FduC447DLUKXMMi4E1gsJANJDtwfTHavB90cnyzxkqy95ko6q59Jn6GiCfu7NQ7Pqm55NiWDQpzMj6oe0yTGuLOfOeSqLIcxZfKV2bZecDHSy7bc1Y5i03Ix2/f02Kc71zx06bU1BwVZXWXiCDYJgxi12hwXHXEdB0blkjljDevFDErfgV6yQeVagu0KpzBe77ujeA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Spam_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
