env:
  global:
    - secure: lBfpRMVXQX/29/4wRs0zdiILivEH/0M1z9wP956uuK/ZcpTCk00xlli1EfjaV5zBu7e5JYgi9UzLIx43yHNPBQbUoxWcTGMiKPp/fB1YpMOW27Cxt3G3gctfpgWBrNDlnNurIKcteLcXVptc43QHJ0gIFL7nfu+szSPPz1r79j8raQnHu+MdpKuDcFwaSK42KRXP4DWbpdpThjeIWp7Ne80U2tfsLTnlIqChBLK0d2k/wdNL0KXw045Pba0H0oRMDqsZ5S0geyR3Q+1I+eU+JIbH1n8NK+16d4MK/267fyzQ4grNhwaSbZDUZte8htKXy95lRMcpYlq6jGbg9DPHsnrBcikHcacAZmGjaekvxv3elmEUs5s/8hmGWzpH03qs9hJZ+BpLi81NU9fhQ2i5LkppiUZ1aVGv2MAufXVbkYRKbb3t2GSJae3UFB4pTO1x7mK9oe8KFAHaVui/SLnM3dAIiME0SsdHfT4uF180xc+3VCBG68LksJnFmw8ow7QVGJ6wRHUYVr+zUcBjJFizUnWKtzHb4kKVIHiVGX488k8uZZM5o0+eDHJfhw6jLNcZGAMfONOmWKsxzDcMM+XNRZZG70hOLQy03mtczhxPPT1AT3jeKwBYii8E9kzhSw6EHPm7IPJAONCKi4klLaG21PqV2Muk78f2KrT8Jj7TO2I=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Spam_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
