env:
  global:
    - secure: HTlz/6SCLeRyvNM+K9rVDWtLnj8kx4+6J2WlrOTL1m4Fapy2voY/C3InqrRjYi0K5j3GEyiK7D9M/4ugC5SDenj1oXF8DP5pdbIfv+tiGJjOOkxeUmnK+IPVzd/71So0a7as+IbHnwEqJh2CGOfsCP1mDKuO1PiMasbFAlI7t0moKrhEkqtTBEhuFgVDzAHYJX36as6w8ADrIRdzS4eNUjhjAuJWBIGDGMwDoZgpPhvpoT91mKm+k22uj8t89w7CG1iwH9X2LFVGgrmUkEDLuZuOz6RNepmz6VgvcV3zRmEJi2U941nYN/ugTwNoRm1aYYmDtySMEH5xw/EfYD7hFggwZnSdKY73m7pnmSEJSuTQyCOF+hDpuUBBv7V8yHQNA3juzEQFoMhAUrc+WS5i02Otxp+dnAvTSTBtbVES1RHMQrCrGEn75Y71pNwkhLZ4SOtlQBhnvjqA1sC68Ny+L/kd+eB8LQcs7DjRCR9xCcOyTfud8y7RmuyHBGLGbkYa61bqeYFyxe4tipuy7JykZoiWF7+IgCo2KedCCLKomwrRgkADVuHYyMcTYhrFYlVS8zoJLN27GVrJPhfA3XMOf4eV9KisV4Gqn0Xld/RtB8Syl9UzyH8U/ZmnoIhpK5Q+Psd9ah5cbZybU296bvXSTidwZ0d6yK7FvWK2y5//5UY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Spam_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
