env:
  global:
    - secure: TJPtpPtgvNLnVWcMurku9ZOQ76jDmve59lcxt1IsW6h8eZPvbfsk7URPSFsxgLcGotKxDJ+grMwrE/DDUZa/MRRXMudNchEwS2EoByefBXCX0A7Dslg66xjxyvrEMRvoL2bZPNmBam+f83LomFXsNkNOu/NnysAumrXZvIhcRmrodkQkW2WsPLW7oQWhhWbSZENZ8QT6DNvLlCP915Vo0U/kkG03e2OovyGj9kZQSfHmhS+LM4qVnjnuONZTDHcdqIhJuMMrgKHTDQ7gyZCAKqKHAE9W7MZvXZnAxQpSBDxSBjJa9pkZAjZsKYP7BdgXHRhqek8dk0t+Zod+KDB6CROzrVrn6DRU+9ui/XudbqdCRns9G2wOMEcHkV5Jd5kRJPPnr0YUHdq/Pgu0diJ8hNWV8z1XBToBDajSl206CmWPn0d64IkgL2tpaLkz9CdNogF3HZUKdahCk1ubBVN7vwXmg32QUkI1yefW9pMdMhCldOE9m8FN9hV3FVEZSvZRTf0XUnCzeUkFklk2TAtcCtOrncD5GunnU7Hhf0K54Zqe27kf5aS3Xnu1aPoyBzcNcEGjcjgXfD/tV3n/dy8vaY6bl0n3qQra6qJr5vLIYjtSpW8rQC3C5epW5RW+Wtuq+XdWCt2qLXOXbgO/Vin/32nsFUKpxS5FAeF/AghK9/c=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Spam_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
