env:
  global:
    - secure: YL7PKkB/5212OWfHq8M6QtQkxZLAMx4S6GErTmlmqYMVMpF25nEzLW5WNDqGAJJRdT4jt7nKOCC/ykGNRPGF5T2LB9VrFxwTZldE2PVCg+PXAO8kFt1AwNimh6WGQ8RmLj8sF0GoJ9JzhOfDgWqVLMRaM5jakJ8m5c1Rz4NHmzA4ksfUge/gVVHpyrPP/v0JbwapEDcxTayrmCK3itKnrtgqY5hFknNt/OX69zJO1C4jIYEjkckfSuLBnq17DXzg/L4InhsOVJtFxzCHflXV+M0B0L6g8bmQojFj3y8GE9tqb9t4O2keB3clbcZIzM/ZXcfgMRbLOSP4MUlrAaMc1e55CvcMT/wvxdLSnyj+ek9hbdZ+hHp3CCB/17cylPqswVqCLrJx10Lh3s7aFTylaxwhkteGiX1riPnoB/yqYzVelfBxdzP3gpxGNu6VwwePghDsZuN5mfF8vMwsMCTxpVCJMQKAFXN3Y7dUvLLOkzhK2bUIttM84hNJcBpIRuf7hurgurBL8JD5KvAGOFTCEYLev3RLPAEzMsquWz4nW3HEQUjklKRQbO0SSxAQ9Eiz8lmFt1rXBsFPVXWYxbERHndyLuZ2JNBx+2DCIV/dp8VDs7c5IYUB2ovkIulHG8CcspnEu+xmENA7KSwt0kegRFU+Mc7hk3dzHRLwh+xgWxs=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Spam_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
